version: '3.8'
name: 'cafe-system-kafka-submodule'

services:
  # --------------------------------------------------------
  # -------------------KAFKA / ZOOKEEPER -------------------
  # --------------------------------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092, EXTERNAL://kafka:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092, EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "28080:8080"
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  kafka-topic-generator:
    image: confluentinc/cp-kafka
    container_name: topic-generator
    depends_on:
      - kafka
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      echo -e 'Current topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      echo -e 'Creating kafka topics'
      echo -e 'Creating update-inventory topic'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic update-inventory-event --replication-factor 1 --partitions 2
      echo -e 'Creating inventory-check topic'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic inventory-check-event --replication-factor 1 --partitions 2
      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "